name: shoppingapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+3
  intl: ^0.16.1
  google_fonts: ^1.1.2
  kopo: ^0.1.1
  flutter_riverpod: ^0.12.1
  cloud_functions: ^0.9.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  state_notifier: ^0.6.0
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  firebase_messaging: ^8.0.0-dev.13
  qr_code_scanner: ^0.3.2
  qr_flutter: ^3.2.0
  flutter_local_notifications: ^3.0.1+6
  url_launcher: ^5.7.10
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  hexagon: ^0.1.0
  sticky_headers: ^0.1.8+1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight : 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoRegular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoMedium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoBold.otf
          weight: 700

  assets:
    - assets/images/set_fcm_page/advertising.png
    - assets/images/category_icon/braces.png
    - assets/images/category_icon/cap.png
    - assets/images/category_icon/dress.png
    - assets/images/category_icon/fragance.png
    - assets/images/category_icon/hoodie.png
    - assets/images/category_icon/sneakers.png
    - assets/images/grade_page/grade_1.png
    - assets/images/grade_page/grade_2.png
    - assets/images/grade_page/grade_3.png
    - assets/images/grade_page/grade_4.png
    - assets/images/grade_page/grade_5.png
    - assets/images/coupon_list_page/checkmark.png
    - assets/images/setting_page/boy.png
    - assets/images/setting_page/woman.png
    - assets/images/setting_page/coins.png
    - assets/images/setting_page/quality.png
    - assets/logo/grocery-cart.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
