import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/widgets.dart';
import 'package:shoppingapp/constants/app_themes.dart';


TextStyle titleStyle = AppThemes.textTheme.bodyText1.copyWith(fontSize: 24,color: Colors.black,fontWeight: FontWeight.w700);
TextStyle subtitleStyle = AppThemes.textTheme.headline2;
TextStyle bodyTitleStyle = AppThemes.textTheme.bodyText1.copyWith(fontSize: 17);
TextStyle bodyContentStyle = AppThemes.textTheme.bodyText2;




Widget useTerms(){
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("여기는 이용약관에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
    ],
  );
}


Widget privacyTerms(){
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 공간은  개인정보처리방침에 관한 글이 들어갈 자리입니다.\n",style:bodyTitleStyle),

    ],
  );
}


Widget gradeTerms(){
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
      Text("이 구역은  본 앱 등급에 관한 전문이 들어갈 자리입니다.\n",style:bodyTitleStyle),
    ],
  );
}


